#include <boost/python.hpp>
#include "ViziaDoomGamePython.h"
#include "ViziaDefines.h"

/*C++ code to expose DoomGamePython via python */

BOOST_PYTHON_MODULE(vizia)
{
    using namespace boost::python;
    using namespace Vizia;

	enum_<ScreenFormat>("ScreenFormat")
		.value("CRCGCB", CRCGCB)
		.value("CRCGCBCA", CRCGCBCA)
		.value("RGB24", RGB24)
		.value("RGBA32", RGBA32)
		.value("ARGB32", ARGB32)
		.value("CBCGCR", CBCGCR)
		.value("CBCGCRCA", CBCGCRCA)
		.value("BGR24", BGR24)
		.value("BGRA32", BGRA32)
		.value("ABGR32", ABGR32);
	enum_<Button>("Button")
        .value("ATTACK", ATTACK)
        .value("USE", USE)
        .value("JUMP", JUMP)
        .value("CROUCH", CROUCH)
        .value("TURN180", TURN180)
        .value("ALTATTACK", ALTATTACK)
        .value("RELOAD", RELOAD)
        .value("ZOOM", ZOOM)
        .value("SPEED", SPEED)
        .value("STRAFE", STRAFE)
        .value("MOVERIGHT", MOVERIGHT)
        .value("MOVELEFT", MOVELEFT)
        .value("BACK", BACK)
        .value("FORWARD", FORWARD)
        .value("RIGHT", RIGHT)
        .value("LEFT", LEFT)
        .value("LOOKUP", LOOKUP)
        .value("LOOKDOWN", LOOKDOWN)
        .value("SELECT_WEAPON1", SELECT_WEAPON1)
        .value("SELECT_WEAPON2", SELECT_WEAPON2)
        .value("SELECT_WEAPON3", SELECT_WEAPON3)
        .value("SELECT_WEAPON4", SELECT_WEAPON4)
        .value("SELECT_WEAPON5", SELECT_WEAPON5)
        .value("SELECT_WEAPON6", SELECT_WEAPON6)
        .value("SELECT_WEAPON7", SELECT_WEAPON7)
        .value("SELECT_NEXT_WEAPON", SELECT_NEXT_WEAPON)
        .value("SELECT_PREV_WEAPON", SELECT_PREV_WEAPON)
        .value("UNDEFINED_BUTTON", UNDEFINED_BUTTON)
        ;
    enum_<GameVar>("GameVar")
        .value("KILLCOUNT", KILLCOUNT)
        .value("ITEMCOUNT", ITEMCOUNT)
        .value("SECRETCOUNT", SECRETCOUNT)
        .value("HEALTH", HEALTH)
        .value("ARMOR", ARMOR)
        .value("SELECTED_WEAPON", SELECTED_WEAPON)
        .value("SELECTED_WEAPON_AMMO", SELECTED_WEAPON_AMMO)
        .value("AMMO1", AMMO1)
        .value("AMMO2", AMMO2)
        .value("AMMO3", AMMO3)
        .value("AMMO4", AMMO4)
        .value("WEAPON1", WEAPON1)
        .value("WEAPON2", WEAPON2)
        .value("WEAPON3", WEAPON3)
        .value("WEAPON4", WEAPON4)
        .value("WEAPON5", WEAPON5)
        .value("WEAPON6", WEAPON6)
        .value("WEAPON7", WEAPON7)
        .value("KEY1", KEY1)
        .value("KEY2", KEY2)
        .value("KEY3", KEY3)
        .value("USER1", USER1)
        .value("USER2", USER2)
        .value("USER3", USER3)
        .value("USER4", USER4)
        .value("USER5", USER5)
        .value("USER6", USER6)
        .value("USER7", USER7)
        .value("USER8", USER8)
        .value("USER9", USER9)
        .value("USER10", USER10)
        .value("USER11", USER11)
        .value("USER12", USER12)
        .value("USER13", USER13)
        .value("USER14", USER14)
        .value("USER15", USER15)
        .value("USER16", USER16)
        .value("USER17", USER17)
        .value("USER18", USER18)
        .value("USER19", USER19)
        .value("USER20", USER20)
        .value("USER21", USER21)
        .value("USER22", USER22)
        .value("USER23", USER23)
        .value("USER24", USER24)
        .value("USER25", USER25)
        .value("USER26", USER26)
        .value("USER27", USER27)
        .value("USER28", USER28)
        .value("USER29", USER29)
        .value("USER30", USER30)
        .value("UNDEFINED_VAR", UNDEFINED_VAR);
	def("DoomTics2Ms", DoomTics2Ms);
	def("Ms2DoomTics", Ms2DoomTics);

    class_<DoomGamePython>("DoomGame", init<>())
		.def("init", &DoomGamePython::init)
		.def("load_config", &DoomGamePython::loadConfig)
		.def("close", &DoomGamePython::close)
		.def("new_episode", &DoomGamePython::newEpisode)
		.def("is_episode_finished", &DoomGamePython::isEpisodeFinished)
		.def("is_new_episode", &DoomGamePython::isNewEpisode)
		.def("make_action",&DoomGamePython::makeAction)
		.def("get_state", &DoomGamePython::getState)
		.def("get_state_format", &DoomGamePython::getStateFormat)
		.def("get_action_format", &DoomGamePython::getActionFormat)
    
        .def("get_game_var", &DoomGamePython::getGameVar)

        .def("isIncludeShapingReward()", &DoomGamePython::isIncludeShapingReward)
        .def("setIncludeShapingReward()", &DoomGamePython::setIncludeShapingReward)

        .def("get_living_reward", &DoomGamePython::getLivingReward)
        .def("set_living_reward", &DoomGamePython::setLivingReward)
        
        .def("get_death_penalty", &DoomGamePython::getDeathPenalty)
        .def("set_death_penalty", &DoomGamePython::setDeathPenalty)
        
        .def("get_last_reward", &DoomGamePython::getLastReward)
        .def("get_summary_reward", &DoomGamePython::getSummaryReward)
        
		.def("add_state_available_var", &DoomGamePython::addStateAvailableVar)
		.def("add_available_button", &DoomGamePython::addAvailableButton)
		.def("set_doom_game_path", &DoomGamePython::setDoomGamePath)
		.def("set_doom_iwad_path", &DoomGamePython::setDoomIwadPath)
		.def("set_doom_file_path", &DoomGamePython::setDoomFilePath)
		.def("set_doom_map", &DoomGamePython::setDoomMap)
		.def("set_doom_skill", &DoomGamePython::setDoomSkill)
		.def("set_doom_config_path", &DoomGamePython::setDoomConfigPath)
		
		.def("set_auto_new_episode", &DoomGamePython::setAutoNewEpisode)
		.def("set_new_episode_on_timeout", &DoomGamePython::setNewEpisodeOnTimeout)
		.def("set_new_episode_on_player_death", &DoomGamePython::setNewEpisodeOnPlayerDeath)
		.def("set_new_episode_on_map_end", &DoomGamePython::setNewEpisodeOnMapEnd)
		
		.def("get_episode_timeout_in_miliseconds", &DoomGamePython::getEpisodeTimeoutInMiliseconds)
		.def("get_episode_timeout_in_doom_tics", &DoomGamePython::getEpisodeTimeoutInDoomTics)
		.def("set_episode_timeout_in_miliseconds", &DoomGamePython::setEpisodeTimeoutInMiliseconds)
		.def("set_episode_timeout_in_doom_tics", &DoomGamePython::setEpisodeTimeoutInDoomTics)
		
		.def("set_screen_resolution", &DoomGamePython::setScreenResolution)
		.def("set_screen_width", &DoomGamePython::setScreenWidth)
		.def("set_screen_height", &DoomGamePython::setScreenHeight)
		.def("set_screen_format", &DoomGamePython::setScreenFormat)
		.def("set_render_hud", &DoomGamePython::setRenderHud)
		.def("set_render_weapon", &DoomGamePython::setRenderWeapon)
		.def("set_render_crosshair", &DoomGamePython::setRenderCrosshair)
		.def("set_render_decals", &DoomGamePython::setRenderDecals)
		.def("set_render_particles", &DoomGamePython::setRenderParticles)
		.def("get_screen_width", &DoomGamePython::getScreenWidth)
		.def("get_screen_height", &DoomGamePython::getScreenHeight)
		.def("get_screen_size", &DoomGamePython::getScreenSize)
		.def("get_screen_pitch", &DoomGamePython::getScreenPitch)
		.def("get_screen_format", &DoomGamePython::getScreenFormat);

}
